#!/bin/bash
# Only proceed if ros2-apt-source package is not installed
if ! dpkg -s ros2-apt-source >/dev/null 2>&1; then
    # Remove old ROS keys and config
    echo -e -n "\n- Remove old ROS keys and config"
    apt-key del "F42E D6FB AB17 C654"
    rm -f /usr/share/keyrings/ros-archive-keyring.gpg
    rm -f /etc/apt/sources.list.d/ros2-latest.list

    # Add new ROS repository package
    echo -e -n "\n- Add new ROS repository package"
    export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
    curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $UBUNTU_CODENAME)_all.deb"
    apt install /tmp/ros2-apt-source.deb
fi

systemctl enable deepracer-core.service